//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 07:09:46 PM CEST 
//


package org.bgbm.biovel.drf.tnr.msg;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.bgbm.biovel.drf.tnr.msg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.bgbm.biovel.drf.tnr.msg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AcceptedName.Classification }
     * 
     */
    public AcceptedName.Classification createAcceptedNameClassification() {
        return new AcceptedName.Classification();
    }

    /**
     * Create an instance of {@link AcceptedName }
     * 
     */
    public AcceptedName createAcceptedName() {
        return new AcceptedName();
    }

    /**
     * Create an instance of {@link TnrMsg.Query }
     * 
     */
    public TnrMsg.Query createTnrMsgQuery() {
        return new TnrMsg.Query();
    }

    /**
     * Create an instance of {@link TnrResponse.OtherName.Info.AcceptedNameUrl }
     * 
     */
    public TnrResponse.OtherName.Info.AcceptedNameUrl createTnrResponseOtherNameInfoAcceptedNameUrl() {
        return new TnrResponse.OtherName.Info.AcceptedNameUrl();
    }

    /**
     * Create an instance of {@link TnrMsg }
     * 
     */
    public TnrMsg createTnrMsg() {
        return new TnrMsg();
    }

    /**
     * Create an instance of {@link TnrResponse.Synonym.Info }
     * 
     */
    public TnrResponse.Synonym.Info createTnrResponseSynonymInfo() {
        return new TnrResponse.Synonym.Info();
    }

    /**
     * Create an instance of {@link TaxonNameType }
     * 
     */
    public TaxonNameType createTaxonNameType() {
        return new TaxonNameType();
    }

    /**
     * Create an instance of {@link TnrResponse.OtherName.Info }
     * 
     */
    public TnrResponse.OtherName.Info createTnrResponseOtherNameInfo() {
        return new TnrResponse.OtherName.Info();
    }

    /**
     * Create an instance of {@link NameType }
     * 
     */
    public NameType createNameType() {
        return new NameType();
    }

    /**
     * Create an instance of {@link AtomisedNameType.SubGenus }
     * 
     */
    public AtomisedNameType.SubGenus createAtomisedNameTypeSubGenus() {
        return new AtomisedNameType.SubGenus();
    }

    /**
     * Create an instance of {@link TnrResponse }
     * 
     */
    public TnrResponse createTnrResponse() {
        return new TnrResponse();
    }

    /**
     * Create an instance of {@link AtomisedNameType }
     * 
     */
    public AtomisedNameType createAtomisedNameType() {
        return new AtomisedNameType();
    }

    /**
     * Create an instance of {@link TnrResponse.Synonym.Info.AcceptedNameUrl }
     * 
     */
    public TnrResponse.Synonym.Info.AcceptedNameUrl createTnrResponseSynonymInfoAcceptedNameUrl() {
        return new TnrResponse.Synonym.Info.AcceptedNameUrl();
    }

    /**
     * Create an instance of {@link SourceType }
     * 
     */
    public SourceType createSourceType() {
        return new SourceType();
    }

    /**
     * Create an instance of {@link AcceptedName.Info }
     * 
     */
    public AcceptedName.Info createAcceptedNameInfo() {
        return new AcceptedName.Info();
    }

    /**
     * Create an instance of {@link TnrMsg.Query.TnrRequest }
     * 
     */
    public TnrMsg.Query.TnrRequest createTnrMsgQueryTnrRequest() {
        return new TnrMsg.Query.TnrRequest();
    }

    /**
     * Create an instance of {@link ScrutinyType }
     * 
     */
    public ScrutinyType createScrutinyType() {
        return new ScrutinyType();
    }

    /**
     * Create an instance of {@link TnrResponse.OtherName }
     * 
     */
    public TnrResponse.OtherName createTnrResponseOtherName() {
        return new TnrResponse.OtherName();
    }

    /**
     * Create an instance of {@link TnrResponse.Synonym }
     * 
     */
    public TnrResponse.Synonym createTnrResponseSynonym() {
        return new TnrResponse.Synonym();
    }

}
