//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.11 at 11:24:29 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bgbm.org/biovel/drf/tnr/msg", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.bgbm.biovel.drf.tnr.msg;
