//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 06:46:29 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bgbm.org/biovel/drf/tnr/msg", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.bgbm.biovel.drf.tnr.msg;
