//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.15 at 07:00:29 PM CET 
//


package org.bgbm.biovel.drf.tnr.msg;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.wordnik.swagger.annotations.ApiModelProperty;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="tnrRequest"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="taxonName" type="{http://bgbm.org/biovel/drf/tnr/msg}taxonName"/&gt;
 *                   &lt;element name="searchMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{http://bgbm.org/biovel/drf/tnr/msg}tnrResponse" maxOccurs="unbounded"/&gt;
 *         &lt;element name="tnrClientStatus" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="checklistId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="statusMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tnrRequest",
    "tnrResponse",
    "tnrClientStatus"
})
@XmlRootElement(name = "query")
public class Query {

    @XmlElement(required = true)
    protected Query.TnrRequest tnrRequest;
    @XmlElement(required = true)
    protected List<TnrResponse> tnrResponse;
    protected List<Query.TnrClientStatus> tnrClientStatus;

    /**
     * Gets the value of the tnrRequest property.
     * 
     * @return
     *     possible object is
     *     {@link Query.TnrRequest }
     *     
     */
    public Query.TnrRequest getTnrRequest() {
        return tnrRequest;
    }

    /**
     * Sets the value of the tnrRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Query.TnrRequest }
     *     
     */
    public void setTnrRequest(Query.TnrRequest value) {
        this.tnrRequest = value;
    }

    /**
     * Gets the value of the tnrResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tnrResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTnrResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TnrResponse }
     * 
     * 
     */
    public List<TnrResponse> getTnrResponse() {
        if (tnrResponse == null) {
            tnrResponse = new ArrayList<TnrResponse>();
        }
        return this.tnrResponse;
    }

    /**
     * Gets the value of the tnrClientStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tnrClientStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTnrClientStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Query.TnrClientStatus }
     * 
     * 
     */
    public List<Query.TnrClientStatus> getTnrClientStatus() {
        if (tnrClientStatus == null) {
            tnrClientStatus = new ArrayList<Query.TnrClientStatus>();
        }
        return this.tnrClientStatus;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="checklistId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="statusMessage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "checklistId",
        "duration",
        "statusMessage"
    })
    public static class TnrClientStatus {

        @XmlElement(required = true)
        protected String checklistId;
        @XmlElement(required = true)
        protected BigDecimal duration;
        @XmlElement(required = true)
        protected String statusMessage;

        /**
         * Gets the value of the checklistId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getChecklistId() {
            return checklistId;
        }

        /**
         * Sets the value of the checklistId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setChecklistId(String value) {
            this.checklistId = value;
        }

        /**
         * Gets the value of the duration property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        @ApiModelProperty("Duration of the request in milliseconds")
        public BigDecimal getDuration() {
            return duration;
        }

        /**
         * Sets the value of the duration property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDuration(BigDecimal value) {
            this.duration = value;
        }

        /**
         * Gets the value of the statusMessage property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        @ApiModelProperty("Status of the request, possible values are 'ok', 'timeout', 'interrupted', 'unsupported search mode'.")
        public String getStatusMessage() {
            return statusMessage;
        }

        /**
         * Sets the value of the statusMessage property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatusMessage(String value) {
            this.statusMessage = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="taxonName" type="{http://bgbm.org/biovel/drf/tnr/msg}taxonName"/&gt;
     *         &lt;element name="searchMode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taxonName",
        "searchMode"
    })
    public static class TnrRequest {

        @XmlElement(required = true)
        protected TaxonName taxonName;
        @XmlElement(required = true)
        protected String searchMode;

        /**
         * Gets the value of the taxonName property.
         * 
         * @return
         *     possible object is
         *     {@link TaxonName }
         *     
         */
        public TaxonName getTaxonName() {
            return taxonName;
        }

        /**
         * Sets the value of the taxonName property.
         * 
         * @param value
         *     allowed object is
         *     {@link TaxonName }
         *     
         */
        public void setTaxonName(TaxonName value) {
            this.taxonName = value;
        }

        /**
         * Gets the value of the searchMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSearchMode() {
            return searchMode;
        }

        /**
         * Sets the value of the searchMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSearchMode(String value) {
            this.searchMode = value;
        }

    }

}
