//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 01:51:32 PM CET 
//


package org.bgbm.biovel.drf.tnr.msg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for taxonName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="taxonName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fullName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="canonicalName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nameLabel" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="atomisedName" type="{http://bgbm.org/biovel/drf/tnr/msg}atomisedName" minOccurs="0"/>
 *         &lt;element name="authorship" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rank" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "taxonName", propOrder = {
    "fullName",
    "canonicalName",
    "nameLabel",
    "atomisedName",
    "authorship",
    "rank"
})
public class TaxonName {

    @XmlElement(required = true)
    protected String fullName;
    @XmlElement(required = true)
    protected String canonicalName;
    protected List<String> nameLabel;
    protected AtomisedName atomisedName;
    protected String authorship;
    protected String rank;

    /**
     * 
     * the  full scientific name, with authorship, publication date information
     * and potentially further taxonomic information.
     *                 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * 
     * Canonical name string consisting of only nomenclatural information,
     * i.e. no authorship or taxonomic hierarchy information
     * with the exception of the necessary
     * placements within Genus or Species.
     *                 
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanonicalName() {
        return canonicalName;
    }

    /**
     * Sets the value of the canonicalName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanonicalName(String value) {
        this.canonicalName = value;
    }

    /**
     * Gets the value of the nameLabel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameLabel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNameLabel() {
        if (nameLabel == null) {
            nameLabel = new ArrayList<String>();
        }
        return this.nameLabel;
    }

    /**
     * Gets the value of the atomisedName property.
     * 
     * @return
     *     possible object is
     *     {@link AtomisedName }
     *     
     */
    public AtomisedName getAtomisedName() {
        return atomisedName;
    }

    /**
     * Sets the value of the atomisedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AtomisedName }
     *     
     */
    public void setAtomisedName(AtomisedName value) {
        this.atomisedName = value;
    }

    /**
     * Gets the value of the authorship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorship() {
        return authorship;
    }

    /**
     * Sets the value of the authorship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorship(String value) {
        this.authorship = value;
    }

    /**
     * Gets the value of the rank property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRank() {
        return rank;
    }

    /**
     * Sets the value of the rank property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRank(String value) {
        this.rank = value;
    }

}
