//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.07 at 02:21:20 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cybertaxonomy.org/utis/tnr/msg", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.cybertaxonomy.utis.tnr.msg;
