//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.09 at 05:13:44 PM CEST 
//


package org.cybertaxonomy.utis.tnr.msg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.fasterxml.jackson.annotation.JsonInclude;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://cybertaxonomy.org/utis/tnr/msg}taxonBase"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="higherClassification" type="{http://cybertaxonomy.org/utis/tnr/msg}higherClassificationElement" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="parentTaxon"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="scientificName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "higherClassification",
    "identifier",
    "parentTaxon"
})
@XmlRootElement(name = "taxon")
@JsonInclude(JsonInclude.Include.NON_EMPTY)
public class Taxon
    extends TaxonBase
{

    protected List<HigherClassificationElement> higherClassification;
    @XmlElement(required = true)
    protected String identifier;
    @XmlElement(required = true)
    protected Taxon.ParentTaxon parentTaxon;

    /**
     * Gets the value of the higherClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the higherClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHigherClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HigherClassificationElement }
     * 
     * 
     */
    public List<HigherClassificationElement> getHigherClassification() {
        if (higherClassification == null) {
            higherClassification = new ArrayList<HigherClassificationElement>();
        }
        return this.higherClassification;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the parentTaxon property.
     * 
     * @return
     *     possible object is
     *     {@link Taxon.ParentTaxon }
     *     
     */
    public Taxon.ParentTaxon getParentTaxon() {
        return parentTaxon;
    }

    /**
     * Sets the value of the parentTaxon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Taxon.ParentTaxon }
     *     
     */
    public void setParentTaxon(Taxon.ParentTaxon value) {
        this.parentTaxon = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="scientificName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "scientificName",
        "identifier"
    })
    public static class ParentTaxon {

        @XmlElement(required = true)
        protected String scientificName;
        @XmlElement(required = true)
        protected String identifier;

        /**
         * Gets the value of the scientificName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScientificName() {
            return scientificName;
        }

        /**
         * Sets the value of the scientificName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScientificName(String value) {
            this.scientificName = value;
        }

        /**
         * Gets the value of the identifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdentifier() {
            return identifier;
        }

        /**
         * Sets the value of the identifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdentifier(String value) {
            this.identifier = value;
        }

    }

}
